// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytcnrnqofxhokpncpwse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Y25ybnFvZnhob2twbmNwd3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODY1NTksImV4cCI6MjA3NDA2MjU1OX0.rqBQV0WIZ74Qx7VHzUqroIV_lEj0qInh5rL4xViFlOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});